# Regenerate the build stamp before every latexmk run.
#
# SRT_Technical_Article.tex \input's version.tex to name the commit it
# describes. version.tex is generated and gitignored, so on a fresh clone it
# does not exist and the document quietly falls back to "unknown" -- which is
# what it did here until 2026-08-27, because nothing in the build ever ran
# docs/update_version.sh. Doing it from latexmk means the stamp cannot be
# forgotten, and it is right even when the build is started from an editor.
#
# This is deliberately perl rather than a call out to update_version.sh: `sh` is
# not on PATH under a plain Windows MiKTeX shell, and a stamp step that silently
# fails there is the same bug again. update_version.sh stays for hand and CI use
# and must keep producing the identical file -- in particular the dirty test,
# which excludes the PDF (it is the output, and is always stale at the moment
# this runs).

sub write_version_tex {
    my $commit = `git rev-parse --short HEAD 2>&1`;
    return if $?;                     # no git, or not a repo: leave the
    chomp $commit;                    # document's own fallback in place

    my $commitdate = `git log -1 "--format=%cd" "--date=format:%Y-%m-%d" 2>&1`;
    return if $?;
    chomp $commitdate;

    my @t = localtime;
    my $builddate = sprintf('%04d-%02d-%02d', $t[5] + 1900, $t[4] + 1, $t[3]);

    my $clean = system('git', '-C', '..', 'diff', '--quiet', 'HEAD', '--', '.',
                       ':(exclude)docs/SRT_Technical_Article.pdf') == 0;
    my $dirty = $clean ? '' : '+local changes';

    open(my $fh, '>', 'version.tex') or return;
    print $fh <<"EOF";
% Generated by docs/.latexmkrc - do not edit by hand.
\\newcommand{\\gitcommit}{$commit}
\\newcommand{\\gitcommitdate}{$commitdate}
\\newcommand{\\gitdirty}{$dirty}
\\newcommand{\\builddate}{$builddate}
EOF
    close $fh;
    warn "version.tex: commit $commit ($commitdate) $dirty\n";
}

write_version_tex();
