#!/bin/sh
# Regenerate docs/version.tex from the current git state.
#
# SRT_Technical_Article.tex \input's this file to stamp the title page with the
# commit the document describes and the date it was built. Run it before
# building the PDF:
#
#     sh docs/update_version.sh && cd docs && latexmk -pdf SRT_Technical_Article.tex
#
# The article falls back to placeholders if version.tex is missing, so a build
# without this step still succeeds - it just cannot say which commit it is.

set -e
cd "$(dirname "$0")/.."

commit=$(git rev-parse --short HEAD)
commitdate=$(git log -1 --format=%cd --date=format:'%Y-%m-%d')
builddate=$(date '+%Y-%m-%d')

# A PDF built from a dirty tree does not describe the commit it names, so say so
# on the title page rather than quietly implying otherwise. The built PDF itself
# is excluded: it is the output, and it is always out of date at the moment this
# runs - it is about to be rebuilt. Including it would make every build claim
# local changes.
if git diff --quiet HEAD -- . ':(exclude)docs/SRT_Technical_Article.pdf' 2>/dev/null; then
    dirty=""
else
    dirty="+local changes"
fi

cat > docs/version.tex <<EOF
% Generated by docs/update_version.sh - do not edit by hand.
\\newcommand{\\gitcommit}{${commit}}
\\newcommand{\\gitcommitdate}{${commitdate}}
\\newcommand{\\gitdirty}{${dirty}}
\\newcommand{\\builddate}{${builddate}}
EOF

echo "docs/version.tex: commit ${commit} (${commitdate}) ${dirty}"
